(function(root) {
  var data = {
  "c01": [
    {
      "id": "c01_q01",
      "source_id": "past-52-law-2",
      "source_chapter": "c01",
      "term": 52,
      "period": 52,
      "subject": "信託法規",
      "number": 2,
      "stem": "某甲將公司債交付信託，已依規定辦理信託公示，但未通知該公司債發行公司，則該信託行為之效力為何？",
      "options": [
        "(1) 無效",
        "(2) 有效，但不能對抗第三人",
        "(3) 無效，但能對抗第三人",
        "(4) 有效，但不能對抗該發行公司"
      ],
      "answer": 3,
      "topic": "成立方式與信託分類",
      "conceptId": "concept-2",
      "frequency": 154,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「成立方式與信託分類」共出現 154 題，章內出題頻率第 1 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c01_q02",
      "source_id": "past-56-law-26",
      "source_chapter": "c01",
      "term": 56,
      "period": 56,
      "subject": "信託法規",
      "number": 26,
      "stem": "信託業收受以公司債為信託財產之信託，經償還後轉化為金錢，併為信託財產運用，係屬於下列何種信託？",
      "options": [
        "(1) 金錢之信託",
        "(2) 金錢債權之信託",
        "(3) 有價證券之信託",
        "(4) 動產之信託"
      ],
      "answer": 2,
      "topic": "成立方式與信託分類",
      "conceptId": "concept-2",
      "frequency": 154,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「成立方式與信託分類」共出現 154 題，章內出題頻率第 1 名。\n💡 本題選自第 56 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c01_q03",
      "source_id": "past-60-law-19",
      "source_chapter": "c01",
      "term": 60,
      "period": 60,
      "subject": "信託法規",
      "number": 19,
      "stem": "下列何種情形為遺囑信託？",
      "options": [
        "(1) 甲生前至銀行簽訂信託契約，並交付銀行新臺幣壹仟萬元，約明以甲之死亡為條件，待甲死亡時，該信託契約方生效",
        "(2) 甲生前至銀行簽訂信託契約，並交付銀行新臺幣壹仟萬元，約明以甲之死亡日為信託期間之起日",
        "(3) 甲於遺囑中指示其遺囑執行人，自其遺產中提撥伍仟萬元由遺囑執行人信託予一慈善機構",
        "(4) 甲依法律規定之方式於遺囑中指定將其部份遺產，指定一受託人成立信託"
      ],
      "answer": 3,
      "topic": "成立方式與信託分類",
      "conceptId": "concept-2",
      "frequency": 154,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「成立方式與信託分類」共出現 154 題，章內出題頻率第 1 名。\n💡 本題選自第 60 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c01_q04",
      "source_id": "past-55-law-9",
      "source_chapter": "c01",
      "term": 55,
      "period": 55,
      "subject": "信託法規",
      "number": 9,
      "stem": "有關受託人之直接管理義務，下列敘述何者錯誤？",
      "options": [
        "(1) 信託行為得另訂第三人代為處理信託事務",
        "(2) 信託行為有不得已之事由者，得使第三人代為處理信託事務",
        "(3) 受託人違反信託直接管理義務時，應就第三人之行為負完全責任",
        "(4) 受託人違反信託直接管理義務，使第三人代為處理信託事務時，該第三人所為法律行為效力可及於信託財產"
      ],
      "answer": 3,
      "topic": "受託人義務報酬與責任",
      "conceptId": "concept-10",
      "frequency": 61,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「受託人義務報酬與責任」共出現 61 題，章內出題頻率第 2 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c01_q05",
      "source_id": "past-52-law-13",
      "source_chapter": "c01",
      "term": 52,
      "period": 52,
      "subject": "信託法規",
      "number": 13,
      "stem": "公益信託之受託人有為違背其職務之行為時，委託人得向下列何機關申請將其解任？",
      "options": [
        "(1) 法院",
        "(2) 檢察機關",
        "(3) 警察機關",
        "(4) 目的事業主管機關"
      ],
      "answer": 3,
      "topic": "公益信託與監督機關",
      "conceptId": "concept-20",
      "frequency": 46,
      "topicRank": 3,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「公益信託與監督機關」共出現 46 題，章內出題頻率第 3 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c01_q06",
      "source_id": "past-51-law-6",
      "source_chapter": "c01",
      "term": 51,
      "period": 51,
      "subject": "信託法規",
      "number": 6,
      "stem": "以應登記或註冊之財產權為信託者，有關信託財產登記之規定，下列敘述何者錯誤？",
      "options": [
        "(1) 非經信託登記，不得對抗第三人",
        "(2) 土地權利登記得以遺囑為之",
        "(3) 以股票為信託者，應向臺灣證券交易所辦理登記",
        "(4) 以有價證券為信託者，應於證券上或其他表彰權利之文件上載明為信託財產"
      ],
      "answer": 2,
      "topic": "登記公示與對抗效力",
      "conceptId": "concept-27",
      "frequency": 33,
      "topicRank": 4,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「登記公示與對抗效力」共出現 33 題，章內出題頻率第 4 名。\n💡 本題選自第 51 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c01_q07",
      "source_id": "past-52-law-32",
      "source_chapter": "c01",
      "term": 52,
      "period": 52,
      "subject": "信託法規",
      "number": 32,
      "stem": "信託財產運用所生之收益及損失應由下列何者享受與承擔？",
      "options": [
        "(1) 受託人",
        "(2) 委託人",
        "(3) 受益人",
        "(4) 從信託契約之約定"
      ],
      "answer": 2,
      "topic": "委託人權利與信託標的",
      "conceptId": "concept-29",
      "frequency": 30,
      "topicRank": 5,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「委託人權利與信託標的」共出現 30 題，章內出題頻率第 5 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c01_q08",
      "source_id": "past-52-law-5",
      "source_chapter": "c01",
      "term": 52,
      "period": 52,
      "subject": "信託法規",
      "number": 5,
      "stem": "信託關係消滅時，於受託人移轉信託財產於歸屬權利人前，信託關係視為存續，該信託關係屬下列何者？",
      "options": [
        "(1) 契約信託",
        "(2) 遺囑信託",
        "(3) 宣言信託",
        "(4) 法定信託"
      ],
      "answer": 3,
      "topic": "終止變更與剩餘財產歸屬",
      "conceptId": "concept-30",
      "frequency": 30,
      "topicRank": 6,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「終止變更與剩餘財產歸屬」共出現 30 題，章內出題頻率第 6 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c01_q09",
      "source_id": "past-54-law-10",
      "source_chapter": "c01",
      "term": 54,
      "period": 54,
      "subject": "信託法規",
      "number": 10,
      "stem": "依信託法規定，受託人違反信託本旨處分信託財產時，下列何者得聲請法院撤銷其處分？",
      "options": [
        "(1) 委託人",
        "(2) 受益人",
        "(3) 信託業主管機關",
        "(4) 法院依職權行使撤銷"
      ],
      "answer": 1,
      "topic": "受益人權利與撤銷救濟",
      "conceptId": "concept-32",
      "frequency": 29,
      "topicRank": 7,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「受益人權利與撤銷救濟」共出現 29 題，章內出題頻率第 7 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c01_q10",
      "source_id": "past-55-law-13",
      "source_chapter": "c01",
      "term": 55,
      "period": 55,
      "subject": "信託法規",
      "number": 13,
      "stem": "下列何者為信託監察人不得行使之權利？",
      "options": [
        "(1) 請求閱覽受託人所作成之信託財產目錄及收支計算表",
        "(2) 對違反規定所為強制執行提起異議之訴權利",
        "(3) 享有信託利益及拋棄信託利益",
        "(4) 對不當管理信託財產之受託人，請求損害賠償"
      ],
      "answer": 2,
      "topic": "信託監察人",
      "conceptId": "concept-34",
      "frequency": 26,
      "topicRank": 8,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「信託監察人」共出現 26 題，章內出題頻率第 8 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (2) 個選項。"
    }
  ],
  "c02": [
    {
      "id": "c02_q01",
      "source_id": "past-57-law-24",
      "source_chapter": "c02",
      "term": 57,
      "period": 57,
      "subject": "信託法規",
      "number": 24,
      "stem": "下列何者不屬於信託業得經營之業務或附屬業務？",
      "options": [
        "(1) 著作權之信託",
        "(2) 擔任信託監察人",
        "(3) 擔任遺囑執行人及遺產管理人",
        "(4) 辦理有價證券買賣融資融券業務"
      ],
      "answer": 3,
      "topic": "業務範圍與禁止保本保息",
      "conceptId": "concept-4",
      "frequency": 116,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「業務範圍與禁止保本保息」共出現 116 題，章內出題頻率第 1 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c02_q02",
      "source_id": "past-55-law-44",
      "source_chapter": "c02",
      "term": 55,
      "period": 55,
      "subject": "信託法規",
      "number": 44,
      "stem": "依信託法及信託業法規定，有關信託業辦理定期會計報告之敘述，下列何者錯誤？",
      "options": [
        "(1) 應依信託契約及主管機關規定為之",
        "(2) 信託財產評審報告每三個月應報告委託人及受益人",
        "(3) 信託契約約定設有信託監察人者，亦應向信託監察人報告",
        "(4) 受託人每年至少定期一次作成信託財產目錄，並編製收支計算表，送交委託人及受益人"
      ],
      "answer": 1,
      "topic": "財產評審報告與會計公告",
      "conceptId": "concept-11",
      "frequency": 59,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「財產評審報告與會計公告」共出現 59 題，章內出題頻率第 2 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c02_q03",
      "source_id": "past-54-law-43",
      "source_chapter": "c02",
      "term": 54,
      "period": 54,
      "subject": "信託法規",
      "number": 43,
      "stem": "下列敘述何者正確？",
      "options": [
        "(1) 非信託業得辦理不特定多數人委託經營信託業法第十六條之信託業務",
        "(2) 信託業得辦理承諾擔保本金或最低收益率之信託業務",
        "(3) 非信託業不得使用信託業或易使人誤認為信託業之名稱",
        "(4) 證券投資信託事業優先適用信託業法之規定"
      ],
      "answer": 2,
      "topic": "經營組織與兼營獨立",
      "conceptId": "concept-16",
      "frequency": 50,
      "topicRank": 3,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「經營組織與兼營獨立」共出現 50 題，章內出題頻率第 3 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c02_q04",
      "source_id": "past-57-law-23",
      "source_chapter": "c02",
      "term": 57,
      "period": 57,
      "subject": "信託法規",
      "number": 23,
      "stem": "原則上信託公司之發起人及股東，同一人或同一關係人持有同一信託公司之股份，分別不得超過其已發行股份總數多少比例？",
      "options": [
        "(1) 百分之三十五",
        "(2) 百分之二十五",
        "(3) 百分之十五",
        "(4) 百分之十"
      ],
      "answer": 1,
      "topic": "設立標準與分支機構",
      "conceptId": "concept-19",
      "frequency": 47,
      "topicRank": 4,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「設立標準與分支機構」共出現 47 題，章內出題頻率第 4 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c02_q05",
      "source_id": "past-54-law-39",
      "source_chapter": "c02",
      "term": 54,
      "period": 54,
      "subject": "信託法規",
      "number": 39,
      "stem": "下列何者情事發生時，信託業須於事實發生之翌日起二個營業日內向主管機關申報？",
      "options": [
        "(1) 因印鑑錯誤而被退票",
        "(2) 更換分支機構經理",
        "(3) 編製營業報告書及財務報告",
        "(4) 簽訂重要契約"
      ],
      "answer": 3,
      "topic": "監理處分罰則與損害賠償",
      "conceptId": "concept-21",
      "frequency": 45,
      "topicRank": 5,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「監理處分罰則與損害賠償」共出現 45 題，章內出題頻率第 5 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c02_q06",
      "source_id": "past-55-law-27",
      "source_chapter": "c02",
      "term": 55,
      "period": 55,
      "subject": "信託法規",
      "number": 27,
      "stem": "依信託業法規定，信託業之利害關係人，指持有信託業或兼營信託業務之銀行已發行股份總數或資本總額多少比例以上者？",
      "options": [
        "(1) 百分之三",
        "(2) 百分之四",
        "(3) 百分之五",
        "(4) 百分之七"
      ],
      "answer": 2,
      "topic": "利害關係人與利益衝突",
      "conceptId": "concept-23",
      "frequency": 43,
      "topicRank": 6,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「利害關係人與利益衝突」共出現 43 題，章內出題頻率第 6 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c02_q07",
      "source_id": "past-52-law-30",
      "source_chapter": "c02",
      "term": 52,
      "period": 52,
      "subject": "信託法規",
      "number": 30,
      "stem": "信託業應提存之賠償準備金，得以下列何者繳存於中央銀行？ A.現金 B.金融債券 C.政府債券 D. 公司債",
      "options": [
        "(1) 僅A、B",
        "(2) 僅A、C",
        "(3) 僅A、D",
        "(4) 僅B、C"
      ],
      "answer": 1,
      "topic": "賠償準備金與盈餘分配",
      "conceptId": "concept-28",
      "frequency": 33,
      "topicRank": 7,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「賠償準備金與盈餘分配」共出現 33 題，章內出題頻率第 7 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c02_q08",
      "source_id": "past-54-law-20",
      "source_chapter": "c02",
      "term": 54,
      "period": 54,
      "subject": "信託法規",
      "number": 20,
      "stem": "呂美與甲銀行簽訂信託契約，由呂美交付新臺幣壹千萬元，指示甲銀行投資於國內上市公司股票，約明信託期間全部信託利益由其姐呂麗享有，則信託關係消滅時，下列敘述何者正確？",
      "options": [
        "(1) 信託財產歸屬之順序，信託契約所定者優先於呂美，呂美優先於呂麗",
        "(2) 信託財產歸屬之順序，信託契約所定者優先於呂麗，呂麗優先於呂美或呂美之繼承人",
        "(3) 信託財產歸屬之順序，信託契約未約定時，呂美與呂麗之順序相同",
        "(4) 信託關係消滅時，受託人所製作之結算書及報告書不須取得呂麗之承認"
      ],
      "answer": 1,
      "topic": "基本義務與契約記載事項",
      "conceptId": "concept-33",
      "frequency": 28,
      "topicRank": 8,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「基本義務與契約記載事項」共出現 28 題，章內出題頻率第 8 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c02_q09",
      "source_id": "past-54-law-37",
      "source_chapter": "c02",
      "term": 54,
      "period": 54,
      "subject": "信託法規",
      "number": 37,
      "stem": "有關共同信託基金受益證券之說明，下列何者正確？",
      "options": [
        "(1) 法律未規定其形式",
        "(2) 法律規定應為不記名式",
        "(3) 法律規定應為記名式",
        "(4) 原則為記名式，經委託人要求可改為不記名式"
      ],
      "answer": 2,
      "topic": "共同信託基金募集與運用",
      "conceptId": "concept-36",
      "frequency": 26,
      "topicRank": 9,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「共同信託基金募集與運用」共出現 26 題，章內出題頻率第 9 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c02_q10",
      "source_id": "past-56-practice-14",
      "source_chapter": "c02",
      "term": 56,
      "period": 56,
      "subject": "信託實務",
      "number": 14,
      "stem": "有關非專業投資人特定金錢信託投資國外有價證券業務項下所能投資之標的，下列何者錯誤？",
      "options": [
        "(1) 經金管會核准之境外基金",
        "(2) 向金管會申報生效之境外基金",
        "(3) 大陸企業赴海外發行之公司債",
        "(4) 符合一定信用評等以上之美國公司債券"
      ],
      "answer": 2,
      "topic": "客戶認識商品適合度與投資人分類",
      "conceptId": "concept-39",
      "frequency": 25,
      "topicRank": 10,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「客戶認識商品適合度與投資人分類」共出現 25 題，章內出題頻率第 10 名。\n💡 本題選自第 56 期，官方公布正確答案為第 (2) 個選項。"
    }
  ],
  "c03": [
    {
      "id": "c03_q01",
      "source_id": "past-52-practice-31",
      "source_chapter": "c03",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 31,
      "stem": "有關企業員工持股信託，下列敘述何者正確？ A.員工中途退出領回信託財產時，應予課所得稅 B.於契約終止時，信託財產僅得折算為金錢方式返還",
      "options": [
        "(1) 僅A",
        "(2) 僅B",
        "(3) AB 皆對",
        "(4) AB 皆錯"
      ],
      "answer": 3,
      "topic": "所得稅與扣繳",
      "conceptId": "concept-14",
      "frequency": 55,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「所得稅與扣繳」共出現 55 題，章內出題頻率第 1 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c03_q02",
      "source_id": "past-55-practice-26",
      "source_chapter": "c03",
      "term": 55,
      "period": 55,
      "subject": "信託實務",
      "number": 26,
      "stem": "企業員工持股信託投資股票所孳生之股利，最終應納入下列何者之綜合所得課稅？",
      "options": [
        "(1) 企業員工持股信託專戶",
        "(2) 受託人",
        "(3) 委託人",
        "(4) 員工持股會"
      ],
      "answer": 2,
      "topic": "所得稅與扣繳",
      "conceptId": "concept-14",
      "frequency": 55,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「所得稅與扣繳」共出現 55 題，章內出題頻率第 1 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c03_q03",
      "source_id": "past-57-practice-49",
      "source_chapter": "c03",
      "term": 57,
      "period": 57,
      "subject": "信託實務",
      "number": 49,
      "stem": "投資人持有金融資產證券化受益證券之利息所得，係採下列何種課稅方式？",
      "options": [
        "(1) 併入綜合所得稅計算",
        "(2) 採分離課稅",
        "(3) 併入營利事業所得稅計算",
        "(4) 不用課稅"
      ],
      "answer": 1,
      "topic": "所得稅與扣繳",
      "conceptId": "concept-14",
      "frequency": 55,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「所得稅與扣繳」共出現 55 題，章內出題頻率第 1 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c03_q04",
      "source_id": "past-56-practice-76",
      "source_chapter": "c03",
      "term": 56,
      "period": 56,
      "subject": "信託實務",
      "number": 76,
      "stem": "委託人羅小姐與甲銀行簽訂信託契約，約定受益人為李小明，後因故受託銀行變更為乙銀行，則信託財產由甲銀行移轉至乙銀行時，必須課徵何種稅捐？",
      "options": [
        "(1) 贈與稅",
        "(2) 營業稅",
        "(3) 契稅",
        "(4) 無須課徵稅捐"
      ],
      "answer": 3,
      "topic": "信託課稅原則與形式移轉",
      "conceptId": "concept-43",
      "frequency": 22,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「信託課稅原則與形式移轉」共出現 22 題，章內出題頻率第 2 名。\n💡 本題選自第 56 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c03_q05",
      "source_id": "past-55-law-46",
      "source_chapter": "c03",
      "term": 55,
      "period": 55,
      "subject": "信託法規",
      "number": 46,
      "stem": "依遺產及贈與稅法規定，他益信託契約如應課徵贈與稅時，其課稅時點，下列何者正確？",
      "options": [
        "(1) 移轉信託財產予受託人之日",
        "(2) 實際享有信託利益之日",
        "(3) 訂定、變更信託契約之日",
        "(4) 移轉信託財產予受益人之日"
      ],
      "answer": 2,
      "topic": "遺產及贈與稅",
      "conceptId": "concept-46",
      "frequency": 21,
      "topicRank": 3,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「遺產及贈與稅」共出現 21 題，章內出題頻率第 3 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c03_q06",
      "source_id": "past-54-law-6",
      "source_chapter": "c03",
      "term": 54,
      "period": 54,
      "subject": "信託法規",
      "number": 6,
      "stem": "因信託關係存續中信託財產所生之地價稅，下列敘述何者錯誤？",
      "options": [
        "(1) 以受託人為納稅義務人",
        "(2) 稅捐機關得逕對欠稅之信託財產強制執行",
        "(3) 受託人不繳納時，稅捐機關不得執行受託人之自有財產",
        "(4) 受託人得逕由信託財產中抵充之"
      ],
      "answer": 2,
      "topic": "土地稅與土地增值稅",
      "conceptId": "concept-50",
      "frequency": 19,
      "topicRank": 4,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「土地稅與土地增值稅」共出現 19 題，章內出題頻率第 4 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c03_q07",
      "source_id": "past-56-law-50",
      "source_chapter": "c03",
      "term": 56,
      "period": 56,
      "subject": "信託法規",
      "number": 50,
      "stem": "受託人依信託本旨移轉信託不動產於委託人以外之歸屬權利人時，應由歸屬權利人估價立契，申報繳納下列何者稅負？",
      "options": [
        "(1) 買賣契稅",
        "(2) 交換契稅",
        "(3) 贈與契稅",
        "(4) 分割契稅"
      ],
      "answer": 2,
      "topic": "房屋稅與契稅",
      "conceptId": "concept-57",
      "frequency": 12,
      "topicRank": 5,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「房屋稅與契稅」共出現 12 題，章內出題頻率第 5 名。\n💡 本題選自第 56 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c03_q08",
      "source_id": "past-56-practice-31",
      "source_chapter": "c03",
      "term": 56,
      "period": 56,
      "subject": "信託實務",
      "number": 31,
      "stem": "員工持股信託之委託人中途退會或信託終了，受託人返還信託財產，依目前相關稅制，委託人需繳納何種稅捐？",
      "options": [
        "(1) 證券交易所得稅",
        "(2) 贈與稅",
        "(3) 遺產稅",
        "(4) 不予課稅"
      ],
      "answer": 3,
      "topic": "員工持股信託的課稅與返還",
      "conceptId": "concept-56",
      "frequency": 12,
      "topicRank": 6,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「員工持股信託的課稅與返還」共出現 12 題，章內出題頻率第 6 名。\n💡 本題選自第 56 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c03_q09",
      "source_id": "past-57-law-46",
      "source_chapter": "c03",
      "term": 57,
      "period": 57,
      "subject": "信託法規",
      "number": 46,
      "stem": "甲以20 萬股上市公司股票成立一信託，信託期間五年，期間孳息歸乙，期滿股票歸甲，假設贈與時中華郵政儲金一年期定期儲金固定利率為1%，契約日當天收盤價每股新臺幣50 元，則甲贈與乙之權利價值為何？ 〔1/(1+1%)5 =0.9515〕",
      "options": [
        "(1) 新臺幣1,000 萬元",
        "(2) 新臺幣 951.5 萬元",
        "(3) 新臺幣48.5 萬元",
        "(4) 零"
      ],
      "answer": 2,
      "topic": "贈與權利價值與折現計算",
      "conceptId": "concept-58",
      "frequency": 10,
      "topicRank": 7,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「贈與權利價值與折現計算」共出現 10 題，章內出題頻率第 7 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c03_q10",
      "source_id": "past-51-practice-78",
      "source_chapter": "c03",
      "term": 51,
      "period": 51,
      "subject": "信託實務",
      "number": 78,
      "stem": "有關信託相關稅負之敘述，下列何者正確？",
      "options": [
        "(1) 個人經由特定金錢信託投資國內基金，分配所得之收益均免納所得稅",
        "(2) 參加企業員工持股信託，投資標的除權後所配得之股利，免納所得稅",
        "(3) 投資不動產投資信託受益證券分配所得之孳息，於次年需申報所得稅",
        "(4) 投資金融資產證券化受益證券之利息所得，採分離課稅方式"
      ],
      "answer": 3,
      "topic": "證券化商品分離課稅與交易稅",
      "conceptId": "concept-61",
      "frequency": 9,
      "topicRank": 8,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「證券化商品分離課稅與交易稅」共出現 9 題，章內出題頻率第 8 名。\n💡 本題選自第 51 期，官方公布正確答案為第 (3) 個選項。"
    }
  ],
  "c04": [
    {
      "id": "c04_q01",
      "source_id": "past-52-practice-9",
      "source_chapter": "c04",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 9,
      "stem": "有關銀行辦理特定金錢信託投資境外基金業務與客戶簽訂之信託契約，下列敘述何者正確？",
      "options": [
        "(1) 期限至少須一個月",
        "(2) 應載明委託人之責任",
        "(3) 應載明受託人之責任",
        "(4) 應載明投資標的之報酬"
      ],
      "answer": 2,
      "topic": "境外基金與國外證券投資",
      "conceptId": "concept-1",
      "frequency": 230,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「境外基金與國外證券投資」共出現 230 題，章內出題頻率第 1 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c04_q02",
      "source_id": "past-54-practice-18",
      "source_chapter": "c04",
      "term": 54,
      "period": 54,
      "subject": "信託實務",
      "number": 18,
      "stem": "客戶經由特定金錢信託以定期定額方式投資境外基金，如因主管機關修改規定致投資標的不符時，銀行應以下列何種方式處理？",
      "options": [
        "(1) 應辦理基金轉換",
        "(2) 應於三年內調整至符合規定",
        "(3) 原則上得按原契約金額繼續投資，至委託人全數贖回為止",
        "(4) 應停止定期定額投資，但原基金可持有至信託契約屆滿或委託人全數贖回為止"
      ],
      "answer": 2,
      "topic": "境外基金與國外證券投資",
      "conceptId": "concept-1",
      "frequency": 230,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「境外基金與國外證券投資」共出現 230 題，章內出題頻率第 1 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c04_q03",
      "source_id": "past-55-practice-12",
      "source_chapter": "c04",
      "term": 55,
      "period": 55,
      "subject": "信託實務",
      "number": 12,
      "stem": "銀行辦理特定金錢信託投資境外基金時，所投資之基金原則上至少必須成立滿幾年？",
      "options": [
        "(1) 半年",
        "(2) 一年",
        "(3) 二年",
        "(4) 三年"
      ],
      "answer": 1,
      "topic": "境外基金與國外證券投資",
      "conceptId": "concept-1",
      "frequency": 230,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「境外基金與國外證券投資」共出現 230 題，章內出題頻率第 1 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c04_q04",
      "source_id": "past-58-practice-77",
      "source_chapter": "c04",
      "term": 58,
      "period": 58,
      "subject": "信託實務",
      "number": 77,
      "stem": "許先生與乙銀行簽訂信託契約辦理金錢信託，指定將新臺幣一百萬元投資於ABC 境外基金，下列敘述何者錯誤？",
      "options": [
        "(1) 就乙銀行而言，新臺幣一百萬元為信託資金",
        "(2) 就該基金公司而言，乙銀行為信託委託人",
        "(3) 就許先生而言，乙銀行為受託人",
        "(4) 就乙銀行而言，其持有之ABC 境外基金受益權單位為信託財產"
      ],
      "answer": 1,
      "topic": "境外基金與國外證券投資",
      "conceptId": "concept-1",
      "frequency": 230,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「境外基金與國外證券投資」共出現 230 題，章內出題頻率第 1 名。\n💡 本題選自第 58 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c04_q05",
      "source_id": "past-52-practice-4",
      "source_chapter": "c04",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 4,
      "stem": "有關特定金錢信託業務，下列敘述何者錯誤？",
      "options": [
        "(1) 委託人應交付金錢做為信託財產",
        "(2) 目前為信託業最主要之信託業務",
        "(3) 受託人對信託財產具運用決定權",
        "(4) 信託業毋須申請兼營證券投資顧問業務"
      ],
      "answer": 2,
      "topic": "金錢信託分類權限與運用",
      "conceptId": "concept-5",
      "frequency": 112,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「金錢信託分類權限與運用」共出現 112 題，章內出題頻率第 2 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c04_q06",
      "source_id": "past-55-practice-6",
      "source_chapter": "c04",
      "term": 55,
      "period": 55,
      "subject": "信託實務",
      "number": 6,
      "stem": "銀行辦理特定金錢信託投資國內外共同基金業務，下列敘述何者錯誤？",
      "options": [
        "(1) 委託人應負擔基金之申購、轉換、贖回等各項費用",
        "(2) 委託人得委託受託銀行以定期定額方式投資",
        "(3) 受託銀行應以委託人名義向國外相關機構辦理投資手續",
        "(4) 受託銀行於委託人交付信託資金後，應發給信託憑證或對帳單或基金存摺以資為憑"
      ],
      "answer": 2,
      "topic": "金錢信託分類權限與運用",
      "conceptId": "concept-5",
      "frequency": 112,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「金錢信託分類權限與運用」共出現 112 題，章內出題頻率第 2 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c04_q07",
      "source_id": "past-57-practice-17",
      "source_chapter": "c04",
      "term": 57,
      "period": 57,
      "subject": "信託實務",
      "number": 17,
      "stem": "特定金錢信託投資國內證券投資信託基金業務之投資指定，應由下列何者為之？",
      "options": [
        "(1) 受託人",
        "(2) 委託人",
        "(3) 受託人或委託人皆可",
        "(4) 得概括授權受託人代為操作"
      ],
      "answer": 1,
      "topic": "金錢信託分類權限與運用",
      "conceptId": "concept-5",
      "frequency": 112,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「金錢信託分類權限與運用」共出現 112 題，章內出題頻率第 2 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c04_q08",
      "source_id": "past-52-practice-24",
      "source_chapter": "c04",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 24,
      "stem": "採行企業員工持股信託之公司辦理現金增資發行新股時，下列敘述何者錯誤？",
      "options": [
        "(1) 享有認購權利之名義人為受託人（信託專戶）本身",
        "(2) 信託專戶應依參與認購新股者之認購權益比例計算暨分配",
        "(3) 委託人得以股東身分直接參與認購",
        "(4) 受託人接獲現金增資通知時，應轉通知委託人"
      ],
      "answer": 2,
      "topic": "員工福利信託特性與制度",
      "conceptId": "concept-9",
      "frequency": 69,
      "topicRank": 3,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「員工福利信託特性與制度」共出現 69 題，章內出題頻率第 3 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c04_q09",
      "source_id": "past-53-practice-29",
      "source_chapter": "c04",
      "term": 53,
      "period": 53,
      "subject": "信託實務",
      "number": 29,
      "stem": "企業員工持股信託之受託人將信託財產以公司股票返還委託人時，該項業務係屬信託業法中所規定之何種信託？",
      "options": [
        "(1) 有價證券之信託",
        "(2) 金錢之信託",
        "(3) 金錢債權及其擔保物權之信託",
        "(4) 其他財產權之信託"
      ],
      "answer": 1,
      "topic": "持股會組織協議與當事人",
      "conceptId": "concept-12",
      "frequency": 59,
      "topicRank": 4,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「持股會組織協議與當事人」共出現 59 題，章內出題頻率第 4 名。\n💡 本題選自第 53 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c04_q10",
      "source_id": "past-57-practice-29",
      "source_chapter": "c04",
      "term": 57,
      "period": 57,
      "subject": "信託實務",
      "number": 29,
      "stem": "企業員工持股信託信託財產之運用方式為何？",
      "options": [
        "(1) 集合運用集合管理",
        "(2) 集合運用分別管理",
        "(3) 分別運用分別管理",
        "(4) 分別運用集合管理"
      ],
      "answer": 1,
      "topic": "投資運用與分別管理",
      "conceptId": "concept-24",
      "frequency": 39,
      "topicRank": 5,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「投資運用與分別管理」共出現 39 題，章內出題頻率第 5 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (1) 個選項。"
    }
  ],
  "c05": [
    {
      "id": "c05_q01",
      "source_id": "past-52-practice-36",
      "source_chapter": "c05",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 36,
      "stem": "有價證券信託之信託公示相關規定，下列何者錯誤？",
      "options": [
        "(1) 應於證券上載明為信託財產",
        "(2) 應向主管機關核備登載",
        "(3) 應於其他表彰權利文件上載明為信託財產",
        "(4) 信託財產登載，應依目的事業主管機關之規定，否則不得對抗第三人"
      ],
      "answer": 1,
      "topic": "證券信託種類與保管差異",
      "conceptId": "concept-15",
      "frequency": 51,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「證券信託種類與保管差異」共出現 51 題，章內出題頻率第 1 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c05_q02",
      "source_id": "past-54-practice-5",
      "source_chapter": "c05",
      "term": 54,
      "period": 54,
      "subject": "信託實務",
      "number": 5,
      "stem": "證券商申請主管機關許可兼營金錢之信託及有價證券之信託，得辦理之特定項目，下列敘述何者錯誤？",
      "options": [
        "(1) 以信託方式辦理財富管理業務",
        "(2) 以信託方式辦理公益之信託",
        "(3) 以信託方式辦理全權委託投資業務",
        "(4) 以信託方式辦理客戶委託保管及運用其款項業務"
      ],
      "answer": 1,
      "topic": "證券信託種類與保管差異",
      "conceptId": "concept-15",
      "frequency": 51,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「證券信託種類與保管差異」共出現 51 題，章內出題頻率第 1 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c05_q03",
      "source_id": "past-55-practice-18",
      "source_chapter": "c05",
      "term": 55,
      "period": 55,
      "subject": "信託實務",
      "number": 18,
      "stem": "管理型有價證券信託與保管業務相比較，下列何者錯誤？",
      "options": [
        "(1) 兩者均須移轉有價證券之占有",
        "(2) 採信託方式時，名義上應由受託人行使股東權利",
        "(3) 兩者均須移轉有價證券之所有權",
        "(4) 採保管方式時，得約定由受任人領取股息"
      ],
      "answer": 2,
      "topic": "證券信託種類與保管差異",
      "conceptId": "concept-15",
      "frequency": 51,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「證券信託種類與保管差異」共出現 51 題，章內出題頻率第 1 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c05_q04",
      "source_id": "past-59-practice-33",
      "source_chapter": "c05",
      "term": 59,
      "period": 59,
      "subject": "信託實務",
      "number": 33,
      "stem": "有關有價證券信託之敘述，下列何者正確？",
      "options": [
        "(1) 無記名式之有價證券不得成為信託之標的",
        "(2) 信託終了時亦必須以有價證券之型態返還剩餘財產",
        "(3) 委託人成立信託時，須交付有價證券予受託人",
        "(4) 信託期間信託財產均須維持有價證券型態，不得變更"
      ],
      "answer": 2,
      "topic": "證券信託種類與保管差異",
      "conceptId": "concept-15",
      "frequency": 51,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「證券信託種類與保管差異」共出現 51 題，章內出題頻率第 1 名。\n💡 本題選自第 59 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c05_q05",
      "source_id": "past-52-practice-33",
      "source_chapter": "c05",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 33,
      "stem": "依證交所規定，有價證券借貸之定價交易相關費率，下列何者正確？ A.依證交所公告之固定借券費率，採逐筆撮合成交 B.證券商向借貸雙方收取之手續費為借券費用0.2% C.證交所向借貸雙方收取之借貸服務費為借券費用1.6%",
      "options": [
        "(1) 僅A",
        "(2) 僅B",
        "(3) 僅C",
        "(4) 僅AC"
      ],
      "answer": 3,
      "topic": "有價證券借貸交易與擔保",
      "conceptId": "concept-22",
      "frequency": 44,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「有價證券借貸交易與擔保」共出現 44 題，章內出題頻率第 2 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c05_q06",
      "source_id": "past-54-practice-32",
      "source_chapter": "c05",
      "term": 54,
      "period": 54,
      "subject": "信託實務",
      "number": 32,
      "stem": "依臺灣證券交易所股份有限公司有價證券借貸辦法規定，有關有價證券借券之敘述，下列何者正確？",
      "options": [
        "(1) 借券人不需付費用",
        "(2) 不得延長借貸期間",
        "(3) 借券人得於約定期限內隨時返還借券",
        "(4) 借貸期間自借貸交易成交日起算，最長不得超過三個月"
      ],
      "answer": 2,
      "topic": "有價證券借貸交易與擔保",
      "conceptId": "concept-22",
      "frequency": 44,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「有價證券借貸交易與擔保」共出現 44 題，章內出題頻率第 2 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c05_q07",
      "source_id": "past-60-practice-37",
      "source_chapter": "c05",
      "term": 60,
      "period": 60,
      "subject": "信託實務",
      "number": 37,
      "stem": "依臺灣證券交易所股份有限公司有價證券借貸辦法規定，除經主管機關核准者外，下列何者得擔任有價證券借貸交易需求之借券人？",
      "options": [
        "(1) 保險公司",
        "(2) 期貨商",
        "(3) 信託業（特定信託契約）",
        "(4) 政府基金"
      ],
      "answer": 1,
      "topic": "有價證券借貸交易與擔保",
      "conceptId": "concept-22",
      "frequency": 44,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「有價證券借貸交易與擔保」共出現 44 題，章內出題頻率第 2 名。\n💡 本題選自第 60 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c05_q08",
      "source_id": "past-52-practice-32",
      "source_chapter": "c05",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 32,
      "stem": "委託人交付新股認購權利證書為信託財產時，屬於下列何種信託業務？",
      "options": [
        "(1) 金錢之信託",
        "(2) 動產之信託",
        "(3) 有價證券之信託",
        "(4) 金錢債權及其擔保物權之信託"
      ],
      "answer": 2,
      "topic": "內部人持股申報與權益行使",
      "conceptId": "concept-25",
      "frequency": 38,
      "topicRank": 3,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「內部人持股申報與權益行使」共出現 38 題，章內出題頻率第 3 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c05_q09",
      "source_id": "past-54-practice-36",
      "source_chapter": "c05",
      "term": 54,
      "period": 54,
      "subject": "信託實務",
      "number": 36,
      "stem": "非信託業者受託有價證券信託之信託財產，其對外未以信託財產名義表彰者，如該受託人為內部人時，其自有財產與信託財產應以下列何種原則申報？",
      "options": [
        "(1) 各自申報原則",
        "(2) 合併申報原則",
        "(3) 信託財產申報原則",
        "(4) 自有財產申報原則"
      ],
      "answer": 1,
      "topic": "內部人持股申報與權益行使",
      "conceptId": "concept-25",
      "frequency": 38,
      "topicRank": 3,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「內部人持股申報與權益行使」共出現 38 題，章內出題頻率第 3 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c05_q10",
      "source_id": "past-56-practice-37",
      "source_chapter": "c05",
      "term": 56,
      "period": 56,
      "subject": "信託實務",
      "number": 37,
      "stem": "信託業具運用決定權之信託，信託財產如取得任一公開發行公司股份超過其已發行股份總額多少比例時，應辦理股權申報？",
      "options": [
        "(1) 百分之一",
        "(2) 百分之三",
        "(3) 百分之五",
        "(4) 百分之十"
      ],
      "answer": 3,
      "topic": "內部人持股申報與權益行使",
      "conceptId": "concept-25",
      "frequency": 38,
      "topicRank": 3,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「內部人持股申報與權益行使」共出現 38 題，章內出題頻率第 3 名。\n💡 本題選自第 56 期，官方公布正確答案為第 (3) 個選項。"
    }
  ],
  "c06": [
    {
      "id": "c06_q01",
      "source_id": "past-52-practice-49",
      "source_chapter": "c06",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 49,
      "stem": "依金融資產證券化條例規定，若特殊目的信託契約並未另有約定，則受益人會議決議指定新受託機構，應以下列何種決議方式為之？",
      "options": [
        "(1) 應有表決權總數三分之二以上受益人之出席，出席受益人表決權過半數之同意行之",
        "(2) 應有表決權總數二分之一以上受益人之出席，出席受益人表決權三分之二之同意行之",
        "(3) 應由全體受益人同意為之",
        "(4) 應有表決權總數二分之一以上受益人之出席，出席受益人表決權過半數之同意行之"
      ],
      "answer": 3,
      "topic": "特殊目的信託公司與參與機構",
      "conceptId": "concept-7",
      "frequency": 89,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「特殊目的信託公司與參與機構」共出現 89 題，章內出題頻率第 1 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c06_q02",
      "source_id": "past-55-practice-47",
      "source_chapter": "c06",
      "term": 55,
      "period": 55,
      "subject": "信託實務",
      "number": 47,
      "stem": "下列何者無法使創始機構之金融資產移轉，取得對抗債務人之效力？",
      "options": [
        "(1) 依民法第二百九十七條之規定，通知債務人",
        "(2) 向債務人寄發已依法公告之證明書者",
        "(3) 創始機構受受託機構之委任而擔任服務機構，負責向債務人收取債權，並已依規定公告",
        "(4) 受託機構與債務人於契約約定寄發依金融資產證券化條例所定公告之證明書者"
      ],
      "answer": 3,
      "topic": "特殊目的信託公司與參與機構",
      "conceptId": "concept-7",
      "frequency": 89,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「特殊目的信託公司與參與機構」共出現 89 題，章內出題頻率第 1 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c06_q03",
      "source_id": "past-59-practice-47",
      "source_chapter": "c06",
      "term": 59,
      "period": 59,
      "subject": "信託實務",
      "number": 47,
      "stem": "依金融資產證券化條例規定，下列何者非屬特殊目的公司得辦理之業務？",
      "options": [
        "(1) 特定資產之管理處分",
        "(2) 發行資產基礎證券",
        "(3) 受讓金融資產等特定資產",
        "(4) 兼營其他非資產證券化業務"
      ],
      "answer": 3,
      "topic": "特殊目的信託公司與參與機構",
      "conceptId": "concept-7",
      "frequency": 89,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「特殊目的信託公司與參與機構」共出現 89 題，章內出題頻率第 1 名。\n💡 本題選自第 59 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c06_q04",
      "source_id": "past-53-practice-46",
      "source_chapter": "c06",
      "term": 53,
      "period": 53,
      "subject": "信託實務",
      "number": 46,
      "stem": "受託機構依規定對不動產投資信託基金之淨資產價值計算，下列敘述何者錯誤？",
      "options": [
        "(1) 應依主管機關核定標準計算淨資產價值",
        "(2) 應每日公告每受益權單位之淨資產價值",
        "(3) 無論不動產價值變動與否均須每日重估",
        "(4) 得依約定以附註揭露方式替代重新估價"
      ],
      "answer": 2,
      "topic": "REIT募集投資標的與限制",
      "conceptId": "concept-8",
      "frequency": 87,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「REIT募集投資標的與限制」共出現 87 題，章內出題頻率第 2 名。\n💡 本題選自第 53 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c06_q05",
      "source_id": "past-56-practice-32",
      "source_chapter": "c06",
      "term": 56,
      "period": 56,
      "subject": "信託實務",
      "number": 32,
      "stem": "不動產投資信託係向不特定人募集資金投資於不動產，屬下列何種信託？",
      "options": [
        "(1) 有價證券信託",
        "(2) 動產信託",
        "(3) 金錢債權信託",
        "(4) 金錢信託"
      ],
      "answer": 3,
      "topic": "REIT募集投資標的與限制",
      "conceptId": "concept-8",
      "frequency": 87,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「REIT募集投資標的與限制」共出現 87 題，章內出題頻率第 2 名。\n💡 本題選自第 56 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c06_q06",
      "source_id": "past-55-practice-41",
      "source_chapter": "c06",
      "term": 55,
      "period": 55,
      "subject": "信託實務",
      "number": 41,
      "stem": "下列何者非屬不動產證券化之特性？",
      "options": [
        "(1) 投資金額較低",
        "(2) 權益可分割性",
        "(3) 經營專業化",
        "(4) 投資單位以分棟分層分戶方式銷售"
      ],
      "answer": 3,
      "topic": "不動產證券化共通規定",
      "conceptId": "concept-18",
      "frequency": 49,
      "topicRank": 3,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「不動產證券化共通規定」共出現 49 題，章內出題頻率第 3 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c06_q07",
      "source_id": "past-57-practice-54",
      "source_chapter": "c06",
      "term": 57,
      "period": 57,
      "subject": "信託實務",
      "number": 54,
      "stem": "有關金融資產證券化受益權與受益證券之敘述，下列何者錯誤？",
      "options": [
        "(1) 可設計為權利層次不同之受益權",
        "(2) 殘值受益人無需藉由受益證券表彰所享有之受益權",
        "(3) 實體受益證券得設計為無記名式",
        "(4) 實體受益證券應由受託機構之代表人簽名、蓋章，並經簽證"
      ],
      "answer": 2,
      "topic": "受益證券募集發行與受益人會議",
      "conceptId": "concept-37",
      "frequency": 26,
      "topicRank": 4,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「受益證券募集發行與受益人會議」共出現 26 題，章內出題頻率第 4 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c06_q08",
      "source_id": "past-50-practice-80",
      "source_chapter": "c06",
      "term": 50,
      "period": 50,
      "subject": "信託實務",
      "number": 80,
      "stem": "有關金融資產證券化之特性，下列敘述何者正確？",
      "options": [
        "(1) 由創始機構發行有價證券",
        "(2) 信用評等之基礎為特殊目的機構之信用評等",
        "(3) 投資人之收益來自特定金融資產之現金流量",
        "(4) 得採提供超額資產、利差帳戶、現金準備帳戶等外部信用增強機制"
      ],
      "answer": 2,
      "topic": "證券化特性與經濟效益",
      "conceptId": "concept-38",
      "frequency": 26,
      "topicRank": 5,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「證券化特性與經濟效益」共出現 26 題，章內出題頻率第 5 名。\n💡 本題選自第 50 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c06_q09",
      "source_id": "past-54-practice-9",
      "source_chapter": "c06",
      "term": 54,
      "period": 54,
      "subject": "信託實務",
      "number": 9,
      "stem": "張三將現金一千萬元交付甲銀行成立信託，並約定五百萬元購買不動產，三百萬元購買股票，二百萬元存放於定期存款，該信託屬信託業法中之下列何種信託？",
      "options": [
        "(1) 不動產信託",
        "(2) 有價證券信託",
        "(3) 金錢信託",
        "(4) 其他財產權信託"
      ],
      "answer": 2,
      "topic": "土地開發與不動產管理信託",
      "conceptId": "concept-45",
      "frequency": 21,
      "topicRank": 6,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「土地開發與不動產管理信託」共出現 21 題，章內出題頻率第 6 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c06_q10",
      "source_id": "past-52-practice-44",
      "source_chapter": "c06",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 44,
      "stem": "下列何者非屬不動產證券化條例所規定之不動產資產信託契約得移轉之財產權？",
      "options": [
        "(1) 已有穩定收入之不動產",
        "(2) 已有穩定收入之不動產相關權利",
        "(3) 已有穩定收入之地上權權利",
        "(4) 依不動產證券化條例發行之受益證券"
      ],
      "answer": 3,
      "topic": "資產移轉債權與債務人通知",
      "conceptId": "concept-51",
      "frequency": 18,
      "topicRank": 7,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「資產移轉債權與債務人通知」共出現 18 題，章內出題頻率第 7 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (3) 個選項。"
    }
  ],
  "c07": [
    {
      "id": "c07_q01",
      "source_id": "past-53-practice-68",
      "source_chapter": "c07",
      "term": 53,
      "period": 53,
      "subject": "信託實務",
      "number": 68,
      "stem": "依我國法令規定，下列何者不須指定保管機構？",
      "options": [
        "(1) 境外華僑及外國人與大陸地區投資人所投資之國內有價證券",
        "(2) 信託資金集合管理運用帳戶之資產",
        "(3) 證券商提存之營業保證金",
        "(4) 保險公司銷售之投資型保險商品專設帳簿之資產"
      ],
      "answer": 1,
      "topic": "基金保管交割與監督責任",
      "conceptId": "concept-3",
      "frequency": 142,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「基金保管交割與監督責任」共出現 142 題，章內出題頻率第 1 名。\n💡 本題選自第 53 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c07_q02",
      "source_id": "past-54-practice-60",
      "source_chapter": "c07",
      "term": 54,
      "period": 54,
      "subject": "信託實務",
      "number": 60,
      "stem": "甲證券投資信託公司於運用基金持有資產前，應先指示乙保管銀行以何者名義開設資產運用帳戶？",
      "options": [
        "(1) 甲證券投資信託公司",
        "(2) 乙銀行總行名義",
        "(3) 乙銀行受託經管甲證券投資信託基金專戶",
        "(4) 甲證券投資信託公司負責人"
      ],
      "answer": 2,
      "topic": "基金保管交割與監督責任",
      "conceptId": "concept-3",
      "frequency": 142,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「基金保管交割與監督責任」共出現 142 題，章內出題頻率第 1 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c07_q03",
      "source_id": "past-56-practice-68",
      "source_chapter": "c07",
      "term": 56,
      "period": 56,
      "subject": "信託實務",
      "number": 68,
      "stem": "有關證券投資信託基金之保管機構，下列敘述何者正確？",
      "options": [
        "(1) 應由其他之證券投資信託公司擔任",
        "(2) 得由募集基金之證券投資信託公司本身擔任",
        "(3) 得經受益人大會決議由證券投資顧問公司擔任",
        "(4) 主要由信託業或銀行信託部擔任"
      ],
      "answer": 3,
      "topic": "基金保管交割與監督責任",
      "conceptId": "concept-3",
      "frequency": 142,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「基金保管交割與監督責任」共出現 142 題，章內出題頻率第 1 名。\n💡 本題選自第 56 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c07_q04",
      "source_id": "past-57-practice-65",
      "source_chapter": "c07",
      "term": 57,
      "period": 57,
      "subject": "信託實務",
      "number": 65,
      "stem": "保管機構保管證券投資信託基金應與委任之證券投資信託公司簽署下列何種契約？",
      "options": [
        "(1) 保管契約",
        "(2) 委任契約",
        "(3) 委託投資契約",
        "(4) 證券投資信託契約"
      ],
      "answer": 3,
      "topic": "基金保管交割與監督責任",
      "conceptId": "concept-3",
      "frequency": 142,
      "topicRank": 1,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「基金保管交割與監督責任」共出現 142 題，章內出題頻率第 1 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c07_q05",
      "source_id": "past-52-practice-56",
      "source_chapter": "c07",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 56,
      "stem": "有關全權委託投資業務之三方權義協定書，下列何者不屬於簽約當事人？",
      "options": [
        "(1) 保管銀行",
        "(2) 委任人",
        "(3) 證券商",
        "(4) 證券投資顧問事業或證券投資信託事業"
      ],
      "answer": 2,
      "topic": "全權委託保管與越權交易",
      "conceptId": "concept-6",
      "frequency": 100,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「全權委託保管與越權交易」共出現 100 題，章內出題頻率第 2 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c07_q06",
      "source_id": "past-55-practice-64",
      "source_chapter": "c07",
      "term": 55,
      "period": 55,
      "subject": "信託實務",
      "number": 64,
      "stem": "全權委託投資業務以委任關係辦理者，下列何者錯誤？",
      "options": [
        "(1) 委任人將資產委託保管機構保管時，應於保管機構開立投資保管帳戶",
        "(2) 原則上每一全權委託投資帳戶之保管銀行以一家為限",
        "(3) 越權交易所需交割之款券，原則上應由委任人負責撥入保管帳戶",
        "(4) 除法令或主管機關另有規定外，原則上不得接受共同之委任"
      ],
      "answer": 2,
      "topic": "全權委託保管與越權交易",
      "conceptId": "concept-6",
      "frequency": 100,
      "topicRank": 2,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「全權委託保管與越權交易」共出現 100 題，章內出題頻率第 2 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c07_q07",
      "source_id": "past-56-practice-77",
      "source_chapter": "c07",
      "term": 56,
      "period": 56,
      "subject": "信託實務",
      "number": 77,
      "stem": "信託業應於會計年度終了後至遲幾個月內，就各集合管理運用帳戶分別編具集合管理運用信託財產年度決算報告？",
      "options": [
        "(1) 一個月",
        "(2) 二個月",
        "(3) 三個月",
        "(4) 四個月"
      ],
      "answer": 3,
      "topic": "單獨及集合管理分類與權限",
      "conceptId": "concept-13",
      "frequency": 59,
      "topicRank": 3,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「單獨及集合管理分類與權限」共出現 59 題，章內出題頻率第 3 名。\n💡 本題選自第 56 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c07_q08",
      "source_id": "past-53-practice-75",
      "source_chapter": "c07",
      "term": 53,
      "period": 53,
      "subject": "信託實務",
      "number": 75,
      "stem": "信託資金集合管理運用帳戶流動性資產占淨資產價值之最低比率為何？",
      "options": [
        "(1) 百分之二",
        "(2) 百分之三",
        "(3) 百分之五",
        "(4) 百分之十"
      ],
      "answer": 2,
      "topic": "集合帳戶投資限制與流動性",
      "conceptId": "concept-17",
      "frequency": 50,
      "topicRank": 4,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「集合帳戶投資限制與流動性」共出現 50 題，章內出題頻率第 4 名。\n💡 本題選自第 53 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c07_q09",
      "source_id": "past-53-practice-72",
      "source_chapter": "c07",
      "term": 53,
      "period": 53,
      "subject": "信託實務",
      "number": 72,
      "stem": "信託業辦理集合管理運用帳戶發生下列何事項時，信託業應即辦理公告？",
      "options": [
        "(1) 淨資產價值跌幅達10%",
        "(2) 淨資產價值跌幅達20%",
        "(3) 帳戶約定條款變更",
        "(4) 受益人不特定"
      ],
      "answer": 2,
      "topic": "集合帳戶申請設置與合併",
      "conceptId": "concept-26",
      "frequency": 34,
      "topicRank": 5,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「集合帳戶申請設置與合併」共出現 34 題，章內出題頻率第 5 名。\n💡 本題選自第 53 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c07_q10",
      "source_id": "past-52-practice-59",
      "source_chapter": "c07",
      "term": 52,
      "period": 52,
      "subject": "信託實務",
      "number": 59,
      "stem": "甲外國機構投資人來台投資，委任乙銀行擔任其保管機構，實務上應以下列何者名義開設新臺幣活期存款帳戶？",
      "options": [
        "(1) 甲",
        "(2) 甲之國外保管機構",
        "(3) 乙銀行",
        "(4) 乙銀行受託保管甲外國機構投資專戶"
      ],
      "answer": 3,
      "topic": "外資全球保管與代理登記",
      "conceptId": "concept-31",
      "frequency": 29,
      "topicRank": 6,
      "frequencyScope": "本章",
      "annotation": "",
      "note": "📊 第 41–62 期本章「外資全球保管與代理登記」共出現 29 題，章內出題頻率第 6 名。\n💡 本題選自第 52 期，官方公布正確答案為第 (3) 個選項。"
    }
  ],
  "c08": [
    {
      "id": "c08_q01",
      "source_id": "past-54-practice-19",
      "source_chapter": "c04",
      "term": 54,
      "period": 54,
      "subject": "信託實務",
      "number": 19,
      "stem": "特定金錢信託業務項下所能投資之境外基金，除經專案核准或基金註冊地經我國承認並公告者外，其成立時間應至少達多久以上？",
      "options": [
        "(1) 六個月",
        "(2) 一年",
        "(3) 二年",
        "(4) 三年"
      ],
      "answer": 1,
      "topic": "境外基金與國外證券投資",
      "conceptId": "concept-1",
      "frequency": 230,
      "topicRank": 1,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「境外基金與國外證券投資」共出現 230 題，全題庫出題頻率第 1 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c08_q02",
      "source_id": "past-57-law-2",
      "source_chapter": "c01",
      "term": 57,
      "period": 57,
      "subject": "信託法規",
      "number": 2,
      "stem": "依信託法規定，委託人於信託成立後六個月內，有下列何種情形者，得推定其行為有害及債權？",
      "options": [
        "(1) 死亡",
        "(2) 失蹤",
        "(3) 受破產之宣告",
        "(4) 受禁治產之宣告"
      ],
      "answer": 2,
      "topic": "成立方式與信託分類",
      "conceptId": "concept-2",
      "frequency": 154,
      "topicRank": 2,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「成立方式與信託分類」共出現 154 題，全題庫出題頻率第 2 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c08_q03",
      "source_id": "past-54-practice-79",
      "source_chapter": "c07",
      "term": 54,
      "period": 54,
      "subject": "信託實務",
      "number": 79,
      "stem": "證券投資信託基金受益人之收益分配請求權，自收益發放日起之消滅時效期間為何？",
      "options": [
        "(1) 一年",
        "(2) 三年",
        "(3) 五年",
        "(4) 十五年"
      ],
      "answer": 2,
      "topic": "基金保管交割與監督責任",
      "conceptId": "concept-3",
      "frequency": 142,
      "topicRank": 3,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「基金保管交割與監督責任」共出現 142 題，全題庫出題頻率第 3 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (2) 個選項。"
    },
    {
      "id": "c08_q04",
      "source_id": "past-57-law-41",
      "source_chapter": "c02",
      "term": 57,
      "period": 57,
      "subject": "信託法規",
      "number": 41,
      "stem": "依證券投資信託事業證券投資顧問事業證券商兼營信託業務管理辦法規定，證券投資信託事業以信託方式經營全權委託投資業務，其接受委託人原始信託財產達新臺幣多少元以上者，符合應申請主管機關許可之一定條件？",
      "options": [
        "(1) 五百萬元",
        "(2) 一千萬元",
        "(3) 一千五百萬元",
        "(4) 二千萬元"
      ],
      "answer": 1,
      "topic": "業務範圍與禁止保本保息",
      "conceptId": "concept-4",
      "frequency": 116,
      "topicRank": 4,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「業務範圍與禁止保本保息」共出現 116 題，全題庫出題頻率第 4 名。\n💡 本題選自第 57 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c08_q05",
      "source_id": "past-55-practice-79",
      "source_chapter": "c04",
      "term": 55,
      "period": 55,
      "subject": "信託實務",
      "number": 79,
      "stem": "甲銀行兼營信託業務，辦理金錢信託、有價證券信託及保管銀行業務，其金錢信託中並無保本保息之代為確定用途信託資金，今該銀行有指撥營運資金新台幣五千萬元，請問甲銀行至少應再提存信託賠償準備金為多少元？",
      "options": [
        "(1) 二千萬元",
        "(2) 三千萬元",
        "(3) 四千萬元",
        "(4) 得以指撥營運資金充當賠償準備金"
      ],
      "answer": 3,
      "topic": "金錢信託分類權限與運用",
      "conceptId": "concept-5",
      "frequency": 112,
      "topicRank": 5,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「金錢信託分類權限與運用」共出現 112 題，全題庫出題頻率第 5 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (3) 個選項。"
    },
    {
      "id": "c08_q06",
      "source_id": "past-59-practice-64",
      "source_chapter": "c07",
      "term": 59,
      "period": 59,
      "subject": "信託實務",
      "number": 64,
      "stem": "保管機構辦理全權委託投資之保管業務時，應將其每月最後營業日製作之委任人投資保管帳戶有價證券明細表，至遲於次月幾日內交付委任人？",
      "options": [
        "(1) 三個營業日",
        "(2) 五個營業日",
        "(3) 七個營業日",
        "(4) 十個營業日"
      ],
      "answer": 1,
      "topic": "全權委託保管與越權交易",
      "conceptId": "concept-6",
      "frequency": 100,
      "topicRank": 6,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「全權委託保管與越權交易」共出現 100 題，全題庫出題頻率第 6 名。\n💡 本題選自第 59 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c08_q07",
      "source_id": "past-55-practice-65",
      "source_chapter": "c06",
      "term": 55,
      "period": 55,
      "subject": "信託實務",
      "number": 65,
      "stem": "受託機構應分別於每營業年度終了及資產信託證券化計畫執行完成後四個月內，作成下列何種書表，向信託監察人報告， 並通知各受益人？ A.資產負債表 B.損益表 C.資產信託證券化計畫書 D.信託財產管理及運用之報告書",
      "options": [
        "(1) A、B、C",
        "(2) A、B、D",
        "(3) A、C、D",
        "(4) B、C、D"
      ],
      "answer": 1,
      "topic": "特殊目的信託公司與參與機構",
      "conceptId": "concept-7",
      "frequency": 89,
      "topicRank": 7,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「特殊目的信託公司與參與機構」共出現 89 題，全題庫出題頻率第 7 名。\n💡 本題選自第 55 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c08_q08",
      "source_id": "past-54-practice-42",
      "source_chapter": "c06",
      "term": 54,
      "period": 54,
      "subject": "信託實務",
      "number": 42,
      "stem": "採募集方式之不動產投資信託基金投資於開發型不動產或不動產相關權利，不得超過該基金信託財產價值之百分之多少？",
      "options": [
        "(1) 十",
        "(2) 十五",
        "(3) 二十",
        "(4) 四十"
      ],
      "answer": 1,
      "topic": "REIT募集投資標的與限制",
      "conceptId": "concept-8",
      "frequency": 87,
      "topicRank": 8,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「REIT募集投資標的與限制」共出現 87 題，全題庫出題頻率第 8 名。\n💡 本題選自第 54 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c08_q09",
      "source_id": "past-45-law-49",
      "source_chapter": "c04",
      "term": 45,
      "period": 45,
      "subject": "信託法規",
      "number": 49,
      "stem": "甲公司提供面值五百萬元約載年利率百分之五之公債，成立他益信託，約定三年內員工業績達成一億元者，可享有該信託財產及其三年間之孳息，請問在尚未有員工達成業績前，其每年利息所得應如何申報？",
      "options": [
        "(1) 由甲公司申報",
        "(2) 由受託人依規定扣繳率申報",
        "(3) 由員工福利委員會申報",
        "(4) 由未來達成業績之員工申報"
      ],
      "answer": 1,
      "topic": "員工福利信託特性與制度",
      "conceptId": "concept-9",
      "frequency": 69,
      "topicRank": 9,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「員工福利信託特性與制度」共出現 69 題，全題庫出題頻率第 9 名。\n💡 本題選自第 45 期，官方公布正確答案為第 (1) 個選項。"
    },
    {
      "id": "c08_q10",
      "source_id": "past-59-law-5",
      "source_chapter": "c01",
      "term": 59,
      "period": 59,
      "subject": "信託法規",
      "number": 5,
      "stem": "甲為委託人、乙為受託人，雙方簽訂信託契約，約定甲交付現金新臺幣一千萬元予乙，乙須將新臺幣一千萬元用於購買特定之Ａ基金，信託期間為一年，則下列敘述何者正確？",
      "options": [
        "(1) 信託契約未另有約定時，信託關係嗣後因甲之死亡而消滅",
        "(2) 信託契約未另有約定時，信託關係嗣後因乙之死亡而消滅",
        "(3) 信託契約未另有約定時，信託關係嗣後因乙之受禁治產宣告而消滅",
        "(4) 依信託契約之約定，信託期間屆滿信託關係消滅"
      ],
      "answer": 3,
      "topic": "受託人義務報酬與責任",
      "conceptId": "concept-10",
      "frequency": 61,
      "topicRank": 10,
      "frequencyScope": "全題庫",
      "annotation": "",
      "note": "📊 第 41–62 期全題庫「受託人義務報酬與責任」共出現 61 題，全題庫出題頻率第 10 名。\n💡 本題選自第 59 期，官方公布正確答案為第 (3) 個選項。"
    }
  ]
};
  if (typeof window !== 'undefined') window.EXAM_BANK_DATA = data;
  if (typeof globalThis !== 'undefined') globalThis.EXAM_BANK_DATA = data;
  if (typeof module !== 'undefined' && module.exports) module.exports = data;
})(typeof window !== 'undefined' ? window : this);
